# Generated by Django 3.1.5 on 2021-01-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Country')),
                ('description', models.TextField(verbose_name='desc')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Work')),
                ('description', models.TextField(verbose_name='desc')),
                ('salary', models.CharField(max_length=150, verbose_name='salary')),
                ('country', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Work',
            },
        ),
    ]
