# Generated by Django 3.1.5 on 2021-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='country',
        ),
        migrations.AddField(
            model_name='work',
            name='country',
            field=models.ManyToManyField(to='work.Country', verbose_name='Country'),
        ),
    ]
