# Generated by Django 3.1.5 on 2021-01-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210121_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='country',
        ),
        migrations.AddField(
            model_name='work',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.country', verbose_name='Country'),
        ),
    ]
